/**
 * Notification Event Keys
 * Based on SquarFT User App Notification Specification
 */

export const NOTIFICATION_EVENTS = {
  // Auth & Profile (1-5)
  AUTH_PHONE_UPDATED: 'AUTH_PHONE_UPDATED',
  USER_WELCOME: 'USER_WELCOME',
  USER_PROFILE_INCOMPLETE: 'USER_PROFILE_INCOMPLETE',
  USER_PROFILE_COMPLETED: 'USER_PROFILE_COMPLETED',
  USER_LOCATION_UPDATED: 'USER_LOCATION_UPDATED',

  // Property Matching & Discovery (6-12)
  PROPERTY_MATCH_FOUND: 'PROPERTY_MATCH_FOUND',
  PROPERTY_SAVED: 'PROPERTY_SAVED',
  PROPERTY_PRICE_DROPPED: 'PROPERTY_PRICE_DROPPED',
  PROPERTY_AVAILABILITY_LOW: 'PROPERTY_AVAILABILITY_LOW',
  PROPERTY_SOLD_OUT: 'PROPERTY_SOLD_OUT',
  SAVED_SEARCH_ALERT: 'SAVED_SEARCH_ALERT',
  SIMILAR_PROPERTY_RECOMMENDATION: 'SIMILAR_PROPERTY_RECOMMENDATION',

  // Visit Management (13-22)
  VISIT_REQUEST_SUBMITTED: 'VISIT_REQUEST_SUBMITTED',
  VISIT_CONFIRMED: 'VISIT_CONFIRMED',
  VISIT_REMINDER_24H: 'VISIT_REMINDER_24H',
  VISIT_REMINDER_2H: 'VISIT_REMINDER_2H',
  VISIT_RESCHEDULED: 'VISIT_RESCHEDULED',
  VISIT_ROUTE_SHARED: 'VISIT_ROUTE_SHARED',
  VISIT_OTP_SENT: 'VISIT_OTP_SENT',
  VISIT_CANCELLED: 'VISIT_CANCELLED',
  VISIT_COMPLETED: 'VISIT_COMPLETED',
  VISIT_FEEDBACK_REQUEST: 'VISIT_FEEDBACK_REQUEST',

  // Deal Management (23-31)
  DEAL_INTEREST_RECORDED: 'DEAL_INTEREST_RECORDED',
  DEAL_CREATED: 'DEAL_CREATED',
  QUOTATION_SHARED: 'QUOTATION_SHARED',
  OFFER_SUBMITTED: 'OFFER_SUBMITTED',
  UNIT_ON_HOLD: 'UNIT_ON_HOLD',
  BOOKING_INITIATED: 'BOOKING_INITIATED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  DEAL_STAGE_UPDATED: 'DEAL_STAGE_UPDATED',
  DEAL_CLOSED_SUCCESSFULLY: 'DEAL_CLOSED_SUCCESSFULLY',

  // Payment Management (32-36)
  TOKEN_PAYMENT_DUE: 'TOKEN_PAYMENT_DUE',
  TOKEN_PAYMENT_RECEIVED: 'TOKEN_PAYMENT_RECEIVED',
  MILESTONE_CREATED: 'MILESTONE_CREATED',
  MILESTONE_DUE_TODAY: 'MILESTONE_DUE_TODAY',
  MILESTONE_PAID: 'MILESTONE_PAID',

  // Document Management (37-40)
  DOCUMENT_REQUIRED: 'DOCUMENT_REQUIRED',
  DOCUMENT_UPLOAD_SUCCESS: 'DOCUMENT_UPLOAD_SUCCESS',
  DOCUMENT_APPROVED: 'DOCUMENT_APPROVED',
  AGREEMENT_READY: 'AGREEMENT_READY',

  // Support & Marketing (41-44)
  SUPPORT_TICKET_CREATED: 'SUPPORT_TICKET_CREATED',
  NEW_PROJECT_LAUNCHED: 'NEW_PROJECT_LAUNCHED',
  PRICE_DROP_CAMPAIGN: 'PRICE_DROP_CAMPAIGN',
  INCOMPLETE_VISIT_BOOKING: 'INCOMPLETE_VISIT_BOOKING',
};

/**
 * Notification Type Categories for UI Icons
 */
export const NOTIFICATION_CATEGORIES = {
  SUCCESS: 'success',
  INFO: 'info',
  WARNING: 'warning',
  ERROR: 'error',
  PROPERTY: 'property',
  VISIT: 'visit',
  DEAL: 'deal',
  PAYMENT: 'payment',
  DOCUMENT: 'document',
  PROFILE: 'profile',
};

/**
 * Map notification events to display categories
 */
export const EVENT_CATEGORY_MAP = {
  // Auth & Profile
  [NOTIFICATION_EVENTS.AUTH_PHONE_UPDATED]: NOTIFICATION_CATEGORIES.PROFILE,
  [NOTIFICATION_EVENTS.USER_WELCOME]: NOTIFICATION_CATEGORIES.SUCCESS,
  [NOTIFICATION_EVENTS.USER_PROFILE_INCOMPLETE]: NOTIFICATION_CATEGORIES.WARNING,
  [NOTIFICATION_EVENTS.USER_PROFILE_COMPLETED]: NOTIFICATION_CATEGORIES.SUCCESS,
  [NOTIFICATION_EVENTS.USER_LOCATION_UPDATED]: NOTIFICATION_CATEGORIES.INFO,

  // Property
  [NOTIFICATION_EVENTS.PROPERTY_MATCH_FOUND]: NOTIFICATION_CATEGORIES.PROPERTY,
  [NOTIFICATION_EVENTS.PROPERTY_SAVED]: NOTIFICATION_CATEGORIES.SUCCESS,
  [NOTIFICATION_EVENTS.PROPERTY_PRICE_DROPPED]: NOTIFICATION_CATEGORIES.SUCCESS,
  [NOTIFICATION_EVENTS.PROPERTY_AVAILABILITY_LOW]: NOTIFICATION_CATEGORIES.WARNING,
  [NOTIFICATION_EVENTS.PROPERTY_SOLD_OUT]: NOTIFICATION_CATEGORIES.WARNING,
  [NOTIFICATION_EVENTS.SAVED_SEARCH_ALERT]: NOTIFICATION_CATEGORIES.PROPERTY,
  [NOTIFICATION_EVENTS.SIMILAR_PROPERTY_RECOMMENDATION]: NOTIFICATION_CATEGORIES.PROPERTY,

  // Visit
  [NOTIFICATION_EVENTS.VISIT_REQUEST_SUBMITTED]: NOTIFICATION_CATEGORIES.INFO,
  [NOTIFICATION_EVENTS.VISIT_CONFIRMED]: NOTIFICATION_CATEGORIES.SUCCESS,
  [NOTIFICATION_EVENTS.VISIT_REMINDER_24H]: NOTIFICATION_CATEGORIES.INFO,
  [NOTIFICATION_EVENTS.VISIT_REMINDER_2H]: NOTIFICATION_CATEGORIES.WARNING,
  [NOTIFICATION_EVENTS.VISIT_RESCHEDULED]: NOTIFICATION_CATEGORIES.INFO,
  [NOTIFICATION_EVENTS.VISIT_ROUTE_SHARED]: NOTIFICATION_CATEGORIES.INFO,
  [NOTIFICATION_EVENTS.VISIT_OTP_SENT]: NOTIFICATION_CATEGORIES.INFO,
  [NOTIFICATION_EVENTS.VISIT_CANCELLED]: NOTIFICATION_CATEGORIES.ERROR,
  [NOTIFICATION_EVENTS.VISIT_COMPLETED]: NOTIFICATION_CATEGORIES.SUCCESS,
  [NOTIFICATION_EVENTS.VISIT_FEEDBACK_REQUEST]: NOTIFICATION_CATEGORIES.INFO,

  // Deal
  [NOTIFICATION_EVENTS.DEAL_INTEREST_RECORDED]: NOTIFICATION_CATEGORIES.SUCCESS,
  [NOTIFICATION_EVENTS.DEAL_CREATED]: NOTIFICATION_CATEGORIES.SUCCESS,
  [NOTIFICATION_EVENTS.QUOTATION_SHARED]: NOTIFICATION_CATEGORIES.DEAL,
  [NOTIFICATION_EVENTS.OFFER_SUBMITTED]: NOTIFICATION_CATEGORIES.INFO,
  [NOTIFICATION_EVENTS.UNIT_ON_HOLD]: NOTIFICATION_CATEGORIES.WARNING,
  [NOTIFICATION_EVENTS.BOOKING_INITIATED]: NOTIFICATION_CATEGORIES.INFO,
  [NOTIFICATION_EVENTS.BOOKING_CONFIRMED]: NOTIFICATION_CATEGORIES.SUCCESS,
  [NOTIFICATION_EVENTS.DEAL_STAGE_UPDATED]: NOTIFICATION_CATEGORIES.INFO,
  [NOTIFICATION_EVENTS.DEAL_CLOSED_SUCCESSFULLY]: NOTIFICATION_CATEGORIES.SUCCESS,

  // Payment
  [NOTIFICATION_EVENTS.TOKEN_PAYMENT_DUE]: NOTIFICATION_CATEGORIES.WARNING,
  [NOTIFICATION_EVENTS.TOKEN_PAYMENT_RECEIVED]: NOTIFICATION_CATEGORIES.SUCCESS,
  [NOTIFICATION_EVENTS.MILESTONE_CREATED]: NOTIFICATION_CATEGORIES.INFO,
  [NOTIFICATION_EVENTS.MILESTONE_DUE_TODAY]: NOTIFICATION_CATEGORIES.WARNING,
  [NOTIFICATION_EVENTS.MILESTONE_PAID]: NOTIFICATION_CATEGORIES.SUCCESS,

  // Document
  [NOTIFICATION_EVENTS.DOCUMENT_REQUIRED]: NOTIFICATION_CATEGORIES.WARNING,
  [NOTIFICATION_EVENTS.DOCUMENT_UPLOAD_SUCCESS]: NOTIFICATION_CATEGORIES.SUCCESS,
  [NOTIFICATION_EVENTS.DOCUMENT_APPROVED]: NOTIFICATION_CATEGORIES.SUCCESS,
  [NOTIFICATION_EVENTS.AGREEMENT_READY]: NOTIFICATION_CATEGORIES.INFO,

  // Support & Marketing
  [NOTIFICATION_EVENTS.SUPPORT_TICKET_CREATED]: NOTIFICATION_CATEGORIES.INFO,
  [NOTIFICATION_EVENTS.NEW_PROJECT_LAUNCHED]: NOTIFICATION_CATEGORIES.PROPERTY,
  [NOTIFICATION_EVENTS.PRICE_DROP_CAMPAIGN]: NOTIFICATION_CATEGORIES.SUCCESS,
  [NOTIFICATION_EVENTS.INCOMPLETE_VISIT_BOOKING]: NOTIFICATION_CATEGORIES.WARNING,
};
